import React from "react";
import Head from "next/head";
import Layout from "../../components/Layout";
import ProjectCard from "../../components/ProjectCard";
import styles from "../../styles/ProjectsPage.module.scss";

const Projects = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ProjectCard />
      </Layout>
    </div>
  );
};

export default Projects;
