import React from "react";
import Layout from "../../components/Layout";
import styles from "../../styles/About.module.scss";
import Head from "next/head";
import Skills from "../../components/Skills";
import AboutC from "../../components/About";
import Funfact from "../../components/Funfact";

const About = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <AboutC slashOrHash="/" who="who am i" />
        <Skills />
        <Funfact />
      </Layout>
    </div>
  );
};

export default About;
