import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import Projects from "../components/Projects";
import Skills from "../components/Skills";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Layout>
          <Hero />
          <Projects />
          <Skills />
        </Layout>
      </div>
    </div>
  );
}
