import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import ProjectsCard from "../components/ProjectsCard";
import Skills from "../components/Skills";
import About from "../components/About";
import Contact from "../components/Contact";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight } from "@fortawesome/free-solid-svg-icons";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mehedi Hasan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Layout>
          <Hero />
          <ProjectsCard
            viewAll={
              <button>
                View All <FontAwesomeIcon icon={faArrowRight} />
              </button>
            }
            slashOrHash="#"
          />
          <Skills />
          <About
            slashOrHash="#"
            readMore={
              <button className={`${styles.btn} btn btnBorder`}>
                Read more <FontAwesomeIcon icon={faArrowRight} />
              </button>
            }
          />
          <Contact slashOrHash="#" />
        </Layout>
      </div>
    </div>
  );
}
