import React from "react";
import Layout from "../../components/Layout";
import styles from "../../styles/Contacts.module.scss";
import Head from "next/head";
import Contactme from "../../components/Contact";

const Contact = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contacts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Contactme slashOrHash="/" />
      </Layout>
    </div>
  );
};

export default Contact;
